"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NEWS_FEED_METRICS = exports.NEWS_FEED_EVENT_TYPES = void 0;
exports.NEWS_FEED_EVENT_TYPES = {
    STORE_CREATED: 'STORE_CREATED',
    STORE_NAME_UPDATED: 'STORE_NAME_UPDATED',
    STORE_RATING_UPDATED: 'STORE_RATING_UPDATED',
    STORE_PROFILE_UPDATED: 'STORE_PROFILE_UPDATED',
    PRODUCT_ADDED: 'PRODUCT_ADDED',
    PRODUCT_UPDATED: 'PRODUCT_UPDATED',
    POPULAR_STORE_CHANGED: 'POPULAR_STORE_CHANGED',
    MOST_ACTIVE_STORE_CHANGED: 'MOST_ACTIVE_STORE_CHANGED',
    MOST_SEARCHED_STORE_CHANGED: 'MOST_SEARCHED_STORE_CHANGED',
};
exports.NEWS_FEED_METRICS = {
    POPULAR_STORE: 'POPULAR_STORE',
    MOST_ACTIVE_STORE: 'MOST_ACTIVE_STORE',
    MOST_SEARCHED_STORE: 'MOST_SEARCHED_STORE',
};
