ALTER TABLE `NewsFeedItem`
  MODIFY COLUMN `type` ENUM(
    'STORE_CREATED',
    'STORE_NAME_UPDATED',
    'STORE_LOCATION_UPDATED',
    'STORE_RATING_UPDATED',
    'STORE_IMAGE_UPDATED',
    'STORE_DELIVERY_UPDATED',
    'STORE_MIN_ORDER_UPDATED',
    'STORE_CONTACT_UPDATED',
    'STORE_PROFILE_UPDATED',
    'PRODUCT_ADDED',
    'PRODUCT_UPDATED',
    'POPULAR_STORE_CHANGED',
    'MOST_ACTIVE_STORE_CHANGED',
    'MOST_SEARCHED_STORE_CHANGED'
  ) NOT NULL;
